apiVersion: v1
kind: Service
metadata:
  name: sentinel-sunpower
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: sunpower
    context: sentinel
    version: v1
